### ISSUE TITLE
Replace logo initial T to Te

### ISSUE THREAD

**Issue by romilrobtsenkov** [rakenduste-programmeerimine-2020s/teemaderegister#21]
New logo should be Te – looks better 🎨 

<img width="68" alt="Screenshot 2020-11-18 at 22 30 40" src="https://user-images.githubusercontent.com/4492641/99584570-cd1ab680-29ed-11eb-8554-eff040a5db65.png">

**Comment by raimop** [comment]
TeRe oleks ka huvitav, kuigi pikem @romilrobtsenkov :D :octocat:

**Comment by romilrobtsenkov** [comment]
Võib olla ka TeRe!
